site_name: 'Documentation'

nav:
  - Model Information: index.md
  - Training Information: training.md
  - Usage Consideration: usage.md
  - Usage Examples: examples.md
  - License: license.md

plugins:
  - techdocs-core
